# The URL the site will be built for
base_url = "https://idec-teams.github.io/2025_OncoStrat_NMU/"

title = "Juice - An intuitive, elegant, and lightweight Zola theme for product sites."
# default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
# compile_sass = true
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Configuration of the Markdown rendering
# theme = "juice"
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "inspired-github"

[extra]

juice_logo_name = "Juice"
juice_logo_path = "images/白字透明.png"
juice_extra_menu = [
    { title = "Home", link = "https://idec-teams.github.io/2025_OncoStrat_NMU/" },
]
# Add page titles here to exclude them from the nav section (case sensitive)
juice_exclude_menu = ["exclude_from_nav"]
repository_url = "https://example.com"
